In [131]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Input, Dropout
from tensorflow.keras.optimizers import SGD, Adam, RMSprop
from tensorflow.keras import regularizers

In [4]:
learning_rate = 3.0
epochs = 60

In [5]:
dataset=mnist.load_data()
(x_train, y_train), (x_test, y_test) = dataset

In [6]:
x_trainv = x_train.reshape(60000, 784)
x_testv = x_test.reshape(10000, 784)
x_trainv = x_trainv.astype('float32')
x_testv = x_testv.astype('float32')

x_trainv /= 255 
x_testv /= 255

In [7]:
num_classes=10
y_trainc = keras.utils.to_categorical(y_train, num_classes)
y_testc = keras.utils.to_categorical(y_test, num_classes)

In [8]:
model = Sequential()
model.add(Dense(800, activation='sigmoid', input_shape=(784,)))
model.add(Dense(400, activation='sigmoid'))
model.add(Dense(200, activation='sigmoid'))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               628000    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 


 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 10)                2010      
                                                                 
Total params: 1030610 (3.93 MB)
Trainable params: 1030610 (3.93 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.compile(loss='categorical_crossentropy',optimizer=Adam(),metrics=['accuracy'])


In [26]:
history = model.fit(x_trainv, y_trainc,
                    batch_size=100,
                    epochs=60,
                    verbose=1,
                    validation_data=(x_testv, y_testc))

Epoch 1/60
600/600 [==============================] - 4s 7ms/step - loss: 0.0046 - accuracy: 0.9985 - val_loss: 0.1020 - val_accuracy: 0.9802
Epoch 2/60
600/600 [==============================] - 4s 7ms/step - loss: 0.0039 - accuracy: 0.9986 - val_loss: 0.1006 - val_accuracy: 0.9823
Epoch 3/60
600/600 [==============================] - 4s 7ms/step - loss: 0.0028 - accuracy: 0.9989 - val_loss: 0.0964 - val_accuracy: 0.9819
Epoch 4/60
600/600 [==============================] - 4s 6ms/step - loss: 0.0017 - accuracy: 0.9995 - val_loss: 0.1019 - val_accuracy: 0.9816
Epoch 5/60
600/600 [==============================] - 4s 7ms/step - loss: 0.0045 - accuracy: 0.9987 - val_loss: 0.0938 - val_accuracy: 0.9841
Epoch 6/60
600/600 [==============================] - 4s 6ms/step - loss: 0.0019 - accuracy: 0.9994 - val_loss: 0.1134 - val_accuracy: 0.9800
Epoch 7/60
600/600 [==============================] - 4s 7ms/step - loss: 0.0017 - accuracy: 0.9994 - val_loss: 0.1124 - val_accuracy: 0.9819
Epoch 

In [27]:
score = model.evaluate(x_testv, y_testc, verbose=1) #evaluar la eficiencia del modelo
print(score)
a=model.predict(x_testv) #predicción de la red entrenada
print(a.shape)
print(a[1])
print("resultado correcto:")
print(y_testc[1])

313/313 [==============================] - 0s 2ms/step - loss: 0.1316 - accuracy: 0.9850
[0.13161922991275787, 0.9850000143051147]
313/313 [==============================] - 0s 1ms/step
(10000, 10)
[1.12677439e-13 6.96237599e-12 9.99999940e-01 3.54307556e-12
 9.29220554e-14 6.90141998e-17 3.64220610e-14 2.49541967e-12
 1.15863395e-11 5.67396011e-19]
resultado correcto:
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
model.save("red.h5")

/usr/local/python/3.10.8/lib/python3.10/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [96]:
model_cargado = tf.keras.models.load_model('red.h5')

In [97]:
#model_cargado.add(Dense(800, activation='sigmoid'))
#model.add(Input(shape=(28,28)))
model_cargado.add(Dense(800, activation='sigmoid', kernel_regularizer=regularizers.L1(0.01),input_shape=(784,)))
model_cargado.add(Dense(400, activation='sigmoid', kernel_regularizer=regularizers.L1(0.01)))
model_cargado.add(Dense(200, activation='sigmoid', kernel_regularizer=regularizers.L1(0.01)))
model_cargado.add(Dense(10, activation='softmax'))
model_cargado.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               628000    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 
 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 10)                2010      
                                                                 
 dense_77 (Dense)            (None, 800)               8800      
                                                                 
 dense_78 (Dense)            (None, 400)               320400    
                                                                 
 dense_79 (Dense)            (None, 200)               8

In [98]:
model_cargado.compile(loss='categorical_crossentropy',optimizer=Adam(),metrics=['accuracy'])


In [99]:
history = model_cargado.fit(x_trainv, y_trainc,
                    batch_size=100,
                    epochs=20,
                    verbose=1,
                    validation_data=(x_testv, y_testc))

Epoch 1/20
600/600 [==============================] - 7s 10ms/step - loss: 10.0084 - accuracy: 0.1039 - val_loss: 2.8038 - val_accuracy: 0.1028
Epoch 2/20
600/600 [==============================] - 6s 10ms/step - loss: 2.8076 - accuracy: 0.1054 - val_loss: 2.8077 - val_accuracy: 0.1135
Epoch 3/20
600/600 [==============================] - 6s 10ms/step - loss: 2.8061 - accuracy: 0.1022 - val_loss: 2.7959 - val_accuracy: 0.1009
Epoch 4/20
600/600 [==============================] - 6s 10ms/step - loss: 2.7997 - accuracy: 0.1030 - val_loss: 2.7938 - val_accuracy: 0.0974
Epoch 5/20
600/600 [==============================] - 6s 10ms/step - loss: 2.7959 - accuracy: 0.1024 - val_loss: 2.7894 - val_accuracy: 0.1010
Epoch 6/20
600/600 [==============================] - 6s 10ms/step - loss: 2.7926 - accuracy: 0.1064 - val_loss: 2.7902 - val_accuracy: 0.0958
Epoch 7/20
600/600 [==============================] - 6s 10ms/step - loss: 2.7878 - accuracy: 0.1047 - val_loss: 2.7900 - val_accuracy: 0.113

In [100]:
score = model_cargado.evaluate(x_testv, y_testc, verbose=1) #evaluar la eficiencia del modelo
print(score)
a=model_cargado.predict(x_testv) #predicción de la red entrenada
print(a.shape)
print(a[1])
print("resultado correcto:")
print(y_testc[1])


313/313 [==============================] - 1s 2ms/step - loss: 2.7762 - accuracy: 0.0974
[2.7762255668640137, 0.09740000218153]
313/313 [==============================] - 1s 2ms/step
(10000, 10)
[0.0849997  0.110884   0.11074723 0.1136461  0.10053072 0.09922662
 0.08095418 0.09062009 0.11727525 0.09111614]
resultado correcto:
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


Se implenta el Regularizador L2


In [101]:
modelo_c = tf.keras.models.load_model('red.h5')

In [102]:
modelo_c.add(Dense(800, activation='sigmoid', kernel_regularizer=regularizers.L2(l2=1e-4),input_shape=(784,)))
modelo_c.add(Dense(400, activation='sigmoid', kernel_regularizer=regularizers.L2(l2=1e-4)))
modelo_c.add(Dense(200, activation='sigmoid', kernel_regularizer=regularizers.L2(l2=1e-4)))
modelo_c.add(Dense(10, activation='softmax'))
modelo_c.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               628000    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 
 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 10)                2010      
                                                                 
 dense_81 (Dense)            (None, 800)               8800      
                                                                 
 dense_82 (Dense)            (None, 400)               320400    
                                                                 
 dense_83 (Dense)            (None, 200)               8

In [103]:
modelo_c.compile(loss='categorical_crossentropy', optimizer = Adam(), metrics = ['accuracy'])

In [104]:
history = modelo_c.fit(x_trainv, y_trainc,
                    batch_size=100,
                    epochs=20,
                    verbose=1,
                    validation_data=(x_testv, y_testc))

Epoch 1/20
600/600 [==============================] - 7s 10ms/step - loss: 0.8017 - accuracy: 0.7980 - val_loss: 0.2520 - val_accuracy: 0.9850
Epoch 2/20
600/600 [==============================] - 6s 10ms/step - loss: 0.1307 - accuracy: 1.0000 - val_loss: 0.2057 - val_accuracy: 0.9849
Epoch 3/20
600/600 [==============================] - 6s 10ms/step - loss: 0.0957 - accuracy: 1.0000 - val_loss: 0.1852 - val_accuracy: 0.9849
Epoch 4/20
600/600 [==============================] - 6s 10ms/step - loss: 0.0773 - accuracy: 1.0000 - val_loss: 0.1732 - val_accuracy: 0.9849
Epoch 5/20
600/600 [==============================] - 6s 10ms/step - loss: 0.0656 - accuracy: 1.0000 - val_loss: 0.1659 - val_accuracy: 0.9850
Epoch 6/20
600/600 [==============================] - 6s 10ms/step - loss: 0.2411 - accuracy: 0.9782 - val_loss: 0.3113 - val_accuracy: 0.9845
Epoch 7/20
600/600 [==============================] - 6s 10ms/step - loss: 0.1014 - accuracy: 1.0000 - val_loss: 0.2062 - val_accuracy: 0.9848

In [105]:
score = modelo_c.evaluate(x_testv, y_testc, verbose=1) #evaluar la eficiencia del modelo
print(score)
a=modelo_c.predict(x_testv) #predicción de la red entrenada
print(a.shape)
print(a[1])
print("resultado correcto:")
print(y_testc[1])


313/313 [==============================] - 1s 2ms/step - loss: 0.1566 - accuracy: 0.9848
[0.15657688677310944, 0.9847999811172485]
313/313 [==============================] - 1s 2ms/step
(10000, 10)
[1.7975469e-04 5.2857911e-04 9.9661165e-01 2.8051066e-04 2.4993028e-04
 5.4565994e-08 3.4016452e-04 4.8565943e-04 7.3275267e-04 5.9087953e-04]
resultado correcto:
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


Implentacion de regularizador L1-L2

In [122]:
model_ = tf.keras.models.load_model('red.h5')

In [123]:
model_
model_.add(Dense(800, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4), input_shape=(784,)))
model_.add(Dense(400, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4)))
model_.add(Dense(200, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5,l2=1e-4)))
model_.add(Dense(10, activation = 'softmax'))
model_.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               628000    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 
 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 10)                2010      
                                                                 
 dense_105 (Dense)           (None, 800)               8800      
                                                                 
 dense_106 (Dense)           (None, 400)               320400    
                                                                 
 dense_107 (Dense)           (None, 200)               8

In [124]:
model_.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

In [125]:
history = model_.fit(x_trainv, y_trainc,
                     batch_size=100,
                     epochs=10,
                     verbose=1,
                     validation_data=(x_testv, y_testc))

Epoch 1/10


600/600 [==============================] - 7s 10ms/step - loss: 0.9280 - accuracy: 0.7987 - val_loss: 0.3691 - val_accuracy: 0.9850
Epoch 2/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2275 - accuracy: 1.0000 - val_loss: 0.2940 - val_accuracy: 0.9847
Epoch 3/10
600/600 [==============================] - 6s 10ms/step - loss: 0.1699 - accuracy: 1.0000 - val_loss: 0.2543 - val_accuracy: 0.9847
Epoch 4/10
600/600 [==============================] - 6s 10ms/step - loss: 0.1338 - accuracy: 1.0000 - val_loss: 0.2267 - val_accuracy: 0.9847
Epoch 5/10
600/600 [==============================] - 6s 10ms/step - loss: 0.1080 - accuracy: 1.0000 - val_loss: 0.2074 - val_accuracy: 0.9848
Epoch 6/10
600/600 [==============================] - 6s 10ms/step - loss: 0.0903 - accuracy: 1.0000 - val_loss: 0.1956 - val_accuracy: 0.9848
Epoch 7/10
600/600 [==============================] - 6s 10ms/step - loss: 0.0785 - accuracy: 1.0000 - val_loss: 0.1871 - val_accuracy: 0.9848
Epoch 8/10

In [128]:
score = model_.evaluate(x_testv, y_testc ,verbose=1 )
print(score)
a=model_.predict(x_testv)
print(a.shape)
print(a[1])
print('resultado correcto')
print(y_testc[1])

 24/313 [=>............................] - ETA: 0s - loss: 0.2025 - accuracy: 0.9844

313/313 [==============================] - 1s 2ms/step - loss: 0.1762 - accuracy: 0.9850
[0.17622146010398865, 0.9850000143051147]
313/313 [==============================] - 1s 2ms/step
(10000, 10)
[3.0444068e-07 9.3572304e-08 9.9597293e-01 5.7606352e-04 1.5724913e-04
 3.6220526e-04 2.2303744e-04 7.0544850e-04 7.3996460e-04 1.2626897e-03]
resultado correcto
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


Implementacion de Dropuot con L1-L2

In [201]:
model_DL=tf.keras.models.load_model('red.h5')

In [202]:
model_DL
model_DL.add(Dense(800, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4), 
                 input_shape=(784,)))
model_DL.add(Dropout(0.5))
model_DL.add(Dense(400, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4)))
model_DL.add(Dense(200, activation='sigmoid', kernel_regularizer=regularizers.L1L2(l1=1e-5,l2=1e-4)))
model_DL.add(Dense(10, activation = 'softmax'))
model_DL.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               628000    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 
 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 10)                2010      
                                                                 
 dense_212 (Dense)           (None, 800)               8800      
                                                                 
 dropout_23 (Dropout)        (None, 800)               0         
                                                                 
 dense_213 (Dense)           (None, 400)               3

In [203]:
model_DL.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

In [204]:
history = model_DL.fit(x_trainv, y_trainc,
                        batch_size=100,
                        epochs=10,
                        verbose=1,
                        validation_data=(x_testv, y_testc))

Epoch 1/10
600/600 [==============================] - 7s 10ms/step - loss: 1.1211 - accuracy: 0.7451 - val_loss: 0.4583 - val_accuracy: 0.9848
Epoch 2/10
600/600 [==============================] - 6s 10ms/step - loss: 0.3403 - accuracy: 0.9964 - val_loss: 0.4002 - val_accuracy: 0.9848
Epoch 3/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2855 - accuracy: 0.9969 - val_loss: 0.3749 - val_accuracy: 0.9849
Epoch 4/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2562 - accuracy: 0.9962 - val_loss: 0.3615 - val_accuracy: 0.9850
Epoch 5/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2339 - accuracy: 0.9964 - val_loss: 0.3465 - val_accuracy: 0.9848
Epoch 6/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2184 - accuracy: 0.9958 - val_loss: 0.3325 - val_accuracy: 0.9848
Epoch 7/10
600/600 [==============================] - 6s 10ms/step - loss: 0.2028 - accuracy: 0.9963 - val_loss: 0.3252 - val_accuracy: 0.9850

In [205]:
score = model_DL.evaluate(x_testv, y_testc, verbose=1)
print(score)
a=model_DL.predict(x_testv)
print(a.shape)
print(a[1])
print('resultado corrcto')
print(y_testc[1])

313/313 [==============================] - 1s 2ms/step - loss: 0.3161 - accuracy: 0.9847
[0.3161310851573944, 0.9847000241279602]
313/313 [==============================] - 1s 2ms/step
(10000, 10)
[5.0035913e-05 4.9199381e-05 9.9954855e-01 6.5272383e-09 1.0071915e-05
 3.5859219e-05 5.8815029e-05 2.4013767e-05 3.8046221e-07 2.2314547e-04]
resultado corrcto
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
